services:
  api:
    container_name: breezy-back-api
    build:
      context: ./api-service
      dockerfile: dockerfile
    ports:
      - "3000"
    command: npm run dev
    volumes:
      - ./api-service:/api
      - node_modules_api:/api/node_modules
    depends_on:
      - db_sql
      - db_mongo
    environment:
      POSTGRES_HOST: db-sql
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_HOST: db-mongo
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    networks:
      - backend

  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - backend

  db_sql:
    image: postgres:16
    container_name: db-sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
        postgres
        -c log_statement=none
        -c logging_collector=off
    networks:
      - backend
  
  db_sql_admin:
    image: dpage/pgadmin4
    container_name: db-sql-admin
    depends_on:
      - db_sql
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@breezy.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - backend

  db_mongo:
    image: mongo:8
    container_name: db-mongo
    command: ["mongod", "--quiet"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  mongo_data:
  node_modules_api:
  pgadmin-data: