events {}

http {
    upstream api_upstream {
        server api:3000;
    }

    upstream auth_upstream {
        server auth:3000;
    }

    upstream user_upstream {
        server user:3000;
    }

    upstream media_upstream {
        server media:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api_upstream/;
        }

        location /api/auth/ {
            proxy_pass http://auth_upstream/;
        }

        location /api/users/ {
            proxy_pass http://user_upstream/;
        }

        location /api/media/ {
            proxy_pass http://media_upstream/;
        }

        location /uploads/ {
            proxy_pass http://media_upstream/uploads/;
        }
    }
}
